name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: django_test
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Specify the Python version you want

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy opencv-python-headless  # Install OpenCV and NumPy
        pip install -r requirements.txt  # Install Django and other dependencies

    - name: Set up PostgreSQL
      run: |
        sudo apt-get install -y postgresql-client
        psql -h localhost -U user -d django_test -c "CREATE EXTENSION IF NOT EXISTS postgis;"

    - name: Run migrations
      run: |
        python manage.py migrate

    - name: Run tests
      run: |
        python manage.py test  # Run Django tests

    - name: Run the face detection script
      run: |
        python detect_faces.py 
        
